services:
  mysql-dev:
    image: mysql:8.0
    container_name: fullstack_authentication_template_dev_data
    environment:
      MYSQL_ROOT_PASSWORD: a_super_secure_root_password
      MYSQL_DATABASE: fullstack_authentication_template_dev
      MYSQL_USER: admin
      MYSQL_PASSWORD: a_super_secure_password
    ports:
      - "3306:3306"
    volumes:
      - fullstack_authentication_template_dev_data:/var/lib/mysql
      - ./apps/backend/db/init:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  fullstack_authentication_template_dev_data:
